package edu.grinnell.csc207.soundsofsorting.sorts;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;

import java.util.ArrayList;
import java.util.List;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     *
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = arr.length; i > 0; i--) {
            for (int j = 0; j < i - 1; j++) {
                events.add(new CompareEvent<>(j, j + 1));
                if (arr[j].compareTo(arr[j + 1]) > 0) {
                    events.add(new SwapEvent<T>(j, j + 1).apply(arr));
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     *
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 0; i < arr.length - 1; i++) {
            int smallestIndex = i;
            for (int j = i + 1; j < arr.length; j++) {
                events.add(new CompareEvent<>(j, smallestIndex));
                if (arr[j].compareTo(arr[smallestIndex]) < 0) {
                    smallestIndex = j;
                }
            }
            if (smallestIndex != i) {
                events.add(new SwapEvent<T>(i, smallestIndex).apply(arr));
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ]
     * </pre>
     *
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 1; i < arr.length; i++) {
            for (int j = i; j > 0; j--) {
                events.add(new CompareEvent<T>(j, j - 1).apply(arr));
                if (arr[j].compareTo(arr[j - 1]) < 0) {
                    events.add(new SwapEvent<T>(j, j - 1).apply(arr));
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     *
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        if (arr.length > 0) {
            mergeSortRecursive(arr, 0, arr.length - 1, events);
        }
        return events;
    }

    /**
     * Implementation of the merge function.
     *
     * @param <T>    the data type
     * @param arr    the array
     * @param low    the starting index
     * @param middle the middle index
     * @param high   the ending index
     * @param events list of sort events
     */
    public static <T extends Comparable<? super T>> void merge(
            T[] arr, int low, int middle, int high, List<SortEvent<T>> events) {
        T[] leftArray = (T[]) new Comparable[middle - low + 1];
        T[] rightArray = (T[]) new Comparable[high - middle];

        System.arraycopy(arr, low, leftArray, 0, leftArray.length);
        System.arraycopy(arr, middle + 1, rightArray, 0, rightArray.length);

        int leftIndex = 0;
        int rightIndex = 0;
        int current = low;

        while (leftIndex < leftArray.length && rightIndex < rightArray.length) {
            events.add(new CompareEvent<T>(low + leftIndex, middle + 1 + rightIndex).apply(arr));
            if (leftArray[leftIndex].compareTo(rightArray[rightIndex]) <= 0) {
                events.add(new CopyEvent<>(current, leftArray[leftIndex]).apply(arr));
                leftIndex++;
            } else {
                events.add(new CopyEvent<>(current, rightArray[rightIndex]).apply(arr));
                rightIndex++;
            }
            current++;
        }

        while (leftIndex < leftArray.length) {
            events.add(new CopyEvent<>(current, leftArray[leftIndex]).apply(arr));
            current++;
            leftIndex++;
        }

        while (rightIndex < rightArray.length) {
            events.add(new CopyEvent<>(current, rightArray[rightIndex]).apply(arr));
            current++;
            rightIndex++;
        }
    }

    /**
     * Recursive function that calls itself and repeatedly divides and conquers.
     *
     * @param <T>    element type
     * @param arr    the array
     * @param left   left index
     * @param right  right index
     * @param events list of sort events
     */
    public static <T extends Comparable<? super T>> void mergeSortRecursive(
            T[] arr, int left, int right, List<SortEvent<T>> events) {
        if (left >= right) {
            return;
        }
        int mid = left + (right - left) / 2;
        mergeSortRecursive(arr, left, mid, events);
        mergeSortRecursive(arr, mid + 1, right, events);
        merge(arr, left, mid, right, events);
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     *
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        if (arr.length > 0) {
            quickSortRecursive(arr, 0, arr.length - 1, events);
        }
        return events;
    }

    /**
     * Recursive function for quicksort.
     *
     * @param <T>    element type
     * @param arr    the array
     * @param left   left index
     * @param right  right index
     * @param events list of sort events
     */
    public static <T extends Comparable<? super T>> void quickSortRecursive(
            T[] arr, int left, int right, List<SortEvent<T>> events) {
        if (left == right) {
            return;
        }

        int pivot = right;
        int i = left - 1;
        int j = left;

        while (j < right) {
            events.add(new CompareEvent<T>(j, pivot).apply(arr));
            if (arr[j].compareTo(arr[pivot]) < 0) {
                i++;
                events.add(new SwapEvent<T>(i, j).apply(arr));
            }
            j++;
        }

        i++;
        events.add(new SwapEvent<T>(i, j).apply(arr));
        pivot = i;

        if (pivot != left) {
            quickSortRecursive(arr, left, pivot - 1, events);
        }
        if (pivot != right) {
            quickSortRecursive(arr, pivot + 1, right, events);
        }
    }

    /**
     * Sorts the array according to the Tim Sort Algorithm.
     *
     * @param <T> the element type
     * @param arr the array to sort
     * @return list of sort events
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> timSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        int minRunSize = 4;

        for (int start = 0; start < arr.length; start += minRunSize) {
            int end = Math.min(arr.length - 1, start + minRunSize - 1);
            timSortInsertion(arr, start, end, events);
        }

        for (int runSize = minRunSize; runSize < arr.length; runSize *= minRunSize) {
            for (int left = 0; left < arr.length; left += 2 * minRunSize) {
                int mid = left + runSize - 1;
                int right = Math.min(left + 2 * runSize - 1, arr.length - 1);
                if (mid < right) {
                    merge(arr, left, mid, right, events);
                }
            }
        }

        return events;
    }

    /**
     * Insertion sort for TimSort.
     *
     * @param <T>    element type
     * @param arr    the array
     * @param start  starting index
     * @param end    ending index
     * @param events list of sort events
     */
    public static <T extends Comparable<? super T>> void timSortInsertion(
            T[] arr, int start, int end, List<SortEvent<T>> events) {
        for (int i = start; i <= end; i++) {
            for (int j = i; j > 0; j--) {
                events.add(new CompareEvent<T>(j, j - 1).apply(arr));
                if (arr[j].compareTo(arr[j - 1]) < 0) {
                    events.add(new SwapEvent<T>(j, j - 1).apply(arr));
                }
            }
        }
    }

    /**
     * Applies all events to array in order.
     *
     * @param <T>    element type
     * @param l      the array
     * @param events list of events
     */
    public static <T> void eventSort(T[] l, List<SortEvent<T>> events) {
        for (SortEvent<T> event : events) {
            event.apply(l);
        }
    }
}
